.module 	variabletest
.title 		Tests variable Module

.include	'variable.def'
.include	'..\common\common.def'

STACK	==	0xFFFF			;SYSTEM STACK

.area	BOOT	(ABS)

.org 	0x0000
	
RST0:
	DI
	LXI	SP,STACK		;INITALIZE STACK
	JMP 	START


;*********************************************************
;* MAIN PROGRAM
;*********************************************************
.area 	_CODE

START:
	MVI	A,8			;SET INTERRUPT MASK
	SIM
	EI				;ENABLE INTERRUPTS

	; SET VAR PTRS
	LXI	H,0x9000
	SHLD	VAR_LOPTR
	SHLD	VAR_HIPTR

;	JMP	TEST_INTNEWFIND
;	JMP	TEST_GET
	JMP	TEST_SET

TEST_INTNEWFIND:	; TEST INTERNAL NEW AND INTERNAL FIND
	; TRY FIND WITH EMPTY VAR AREA
	MVI	B,'A			; CHECK FOR 'A'
	MVI	C,0
	CALL	VAR_INTERNALGET		; RESULT: HL = 0

	; CREATE NEW
	CALL	VAR_INTERNALNEW
	
	; TRY FIND AGAIN
	MVI	B,'A			; CHECK FOR 'A'
	MVI	C,0
	CALL	VAR_INTERNALGET		; RESULT: HL = VAR_LOPTR

	; TRY FIND NON EXISTING
	MVI	B,'B			; CHECK FOR 'B'
	MVI	C,0
	CALL	VAR_INTERNALGET		; RESULT: HL = 0

	; CREATE NEW VARIABLE
	MVI	B,'A			; CREATE 'AB'
	MVI	C,'B
	CALL	VAR_INTERNALNEW		

	; FIND IT
	MVI	B,'A			; CHECK FOR 'AB'
	MVI	C,'B
	CALL	VAR_INTERNALGET		; RESULT: ADDRESS OF 'AB'

	; FIND UNKNOWN
	MVI	B,'A			; CHECK FOR 'AC'
	MVI	C,'C
	CALL	VAR_INTERNALGET		; RESULT: HL = 0
	

TEST_GET:
	; NEW VARIABLE 'T0'
	MVI	B,'T			; CHECK FOR 'T0'
	MVI	C,'0
	LXI	H,VAR_TEMP1		; DESTINATION
	CALL	VAR_GET

TEST_SET:
	; NEW VARIABLE 'T0'
	MVI	A,SID_CINT
	STA	VAR_TEMP1
	LXI	H,0x1234
	SHLD	VAR_TEMP1+1	
	
	MVI	B,'T			; SET 'T0'
	MVI	C,'0
	LXI	H,VAR_TEMP1		; DESTINATION
	CALL	VAR_SET

	; NEW VARIABLE 'T1'
	MVI	A,SID_CINT
	STA	VAR_TEMP1
	LXI	H,0x4567
	SHLD	VAR_TEMP1+1	
	
	MVI	B,'T			; SET 'T1'
	MVI	C,'1
	LXI	H,VAR_TEMP1		; DESTINATION
	CALL	VAR_SET

	; VARIABLE 'T1' (EXISTING VARIABLE)
	MVI	A,SID_CINT
	STA	VAR_TEMP1
	LXI	H,0x6666
	SHLD	VAR_TEMP1+1	
	
	MVI	B,'T			; SET 'T1'
	MVI	C,'1
	LXI	H,VAR_TEMP1		; DESTINATION
	CALL	VAR_SET


LOOP:
	JMP	LOOP


;TESTSTR1:	.asciz	''

.area	DATA	(REL,CON)

;OUTSTR:	.ds 128

