.module 	variabletest
.title 		Tests variable Module

.include	'variable.def'

STACK	==	0xFFFF			;SYSTEM STACK

.area	BOOT	(ABS)

.org 	0x0000
	
RST0:
	DI
	LXI	SP,STACK		;INITALIZE STACK
	JMP 	START


;*********************************************************
;* MAIN PROGRAM
;*********************************************************
.area 	_CODE

START:

	MVI	A,8			;SET INTERRUPT MASK
	SIM
	EI				;ENABLE INTERRUPTS

	; SET VAR PTRS
	LXI	H,0x9000
	SHLD	VAR_LOPTR
	SHLD	VAR_HIPTR


	JMP	TEST_INTNEWFIND

TEST_INTNEWFIND:	; TEST INTERNAL NEW AND INTERNAL FIND
	
	; TRY FIND WITH EMPTY VAR AREA
	MVI	B,'A			; CHECK FOR 'A'
	MVI	C,0
	CALL	VAR_INTERNALGET		; RESULT: HL = 0

	; CREATE NEW
	CALL	VAR_INTERNALNEW
	
	; TRY FIND AGAIN
	MVI	B,'A			; CHECK FOR 'A'
	MVI	C,0
	CALL	VAR_INTERNALGET		; RESULT: HL = VAR_LOPTR

	; TRY FIND NON EXISTING
	MVI	B,'B			; CHECK FOR 'B'
	MVI	C,0
	CALL	VAR_INTERNALGET		; RESULT: HL = 0

	; CREATE NEW VARIABLE
	MVI	B,'A			; CREATE 'AB'
	MVI	C,'B
	CALL	VAR_INTERNALNEW		

	; FIND IT
	MVI	B,'A			; CHECK FOR 'AB'
	MVI	C,'B
	CALL	VAR_INTERNALGET		; RESULT: ADDRESS OF 'AB'

	; FIND UNKNOWN
	MVI	B,'A			; CHECK FOR 'AC'
	MVI	C,'C
	CALL	VAR_INTERNALGET		; RESULT: HL = 0
	

LOOP:
	JMP	LOOP


TESTSTR1:	.asciz	''

.area	DATA	(REL,CON)
TESTSTR100:	.asciz	''

OUTSTR:		.ds 128

